name: Deploy to Firebase
on:
  push:
    branches: [ Main ] # CORRECTED: Changed 'main' to 'Main' to match the repository's branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install root deps
        run: npm ci

      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          # ...other NEXT_ envs

      - name: Install Firebase Tools
        run: npm i -g firebase-tools

      - name: Functions deps
        working-directory: functions
        run: npm ci

      - name: Deploy (Hosting + Functions + Rules + Indexes)
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only firestore:rules,firestore:indexes,storage,functions,hosting --token "${{ secrets.FIREBASE_TOKEN }}"
