name: Purge Large File From History

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to remove from history (exact path)'
        required: true
        default: '_import/blr_world_hub.zip'

permissions:
  contents: write

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-filter-repo || pipx install git-filter-repo || pip install git-filter-repo
          git --version

      - name: Remove large file from history
        run: |
          git filter-repo --force --invert-paths --path "${{ github.event.inputs.path }}"

      - name: Push rewritten history (force)
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git push origin --force --all
          git push origin --force --tags